defaults:
  - task: unlearning_enpo
  - hydra: default
  # Allow the model to overwrite the settings below
  - _self_
  - pre_trained_llm: phi-3-mini-4k-instruct
  - experiment: ~

unlearning_target: "1_Stephen_King"

skip_initial_eval: true

seed: ~

name: unlearning-${unlearning_target}
exp: atu-unlearning

wandb:
  id: ~
  entity: "1137113080-wuhan-university" # Your wandb entity (or use "1137113080" if that's your username)
  project: ${exp}
  group: ~
  name: ${name}
  mode: ~

hydra:
  job:
    name: ${exp}

trainer:
  accelerator: auto
  devices: auto
  max_epochs: -1
  log_every_n_steps: 10

early_stopping: ~

matmul_precision: medium
